/*
 * Floatplane REST API
 *
 * The version of the OpenAPI document: 3.9.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FloatplaneAPIClientCSharp.Client;
using FloatplaneAPIClientCSharp.Api;
// uncomment below to import models
//using FloatplaneAPIClientCSharp.Model;

namespace FloatplaneAPIClientCSharp.Test.Api
{
	/// <summary>
	///  Class for testing AuthV2Api
	/// </summary>
	/// <remarks>
	/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
	/// Please update the test case below to test the API endpoint.
	/// </remarks>
	public class AuthV2ApiTests : IDisposable
	{
		private AuthV2Api instance;

		public AuthV2ApiTests()
		{
			instance = new AuthV2Api();
			ApiTestHelper.SetStrictSerializerSettings(instance, instance.Client);
		}

		public void Dispose()
		{
			// Cleanup when everything is done.
		}

		/// <summary>
		/// Test CheckFor2faLogin
		/// </summary>
		[Fact]
		public void CheckFor2faLoginTest()
		{
			// TODO uncomment below to test the method and replace null with proper value
			//CheckFor2faLoginRequest checkFor2faLoginRequest = null;
			//var response = instance.CheckFor2faLogin(checkFor2faLoginRequest);
			//Assert.IsType<AuthLoginV2Response>(response);
		}

		/// <summary>
		/// Test Login
		/// </summary>
		[Fact]
		public void LoginTest()
		{
			// TODO uncomment below to test the method and replace null with proper value
			//AuthLoginV2Request authLoginV2Request = null;
			//var response = instance.Login(authLoginV2Request);
			//Assert.IsType<AuthLoginV2Response>(response);
		}

		/// <summary>
		/// Test Logout
		/// </summary>
		[Fact]
		public void LogoutTest()
		{
			// TODO uncomment below to test the method and replace null with proper value
			//var response = instance.Logout();
			//Assert.IsType<string>(response);
		}
	}
}
