/*
 * Floatplane REST API
 *
 * The version of the OpenAPI document: 3.9.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FloatplaneAPIClientCSharp.Client;
using FloatplaneAPIClientCSharp.Api;
using FloatplaneAPIClientCSharp.Model;

namespace FloatplaneAPIClientCSharp.Test.Api
{
	/// <summary>
	///  Class for testing AuthV3Api
	/// </summary>
	/// <remarks>
	/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
	/// Please update the test case below to test the API endpoint.
	/// </remarks>
	public class AuthV3ApiTests : IDisposable
	{
		private AuthV3Api instance;

		public AuthV3ApiTests()
		{
			instance = new AuthV3Api();
			ApiTestHelper.SetStrictSerializerSettings(instance, instance.Client);
		}

		public void Dispose()
		{
			// Cleanup when everything is done.
		}

		/// <summary>
		/// Test GetCaptchaInfo
		/// </summary>
		[Fact]
		public void GetCaptchaInfoTest()
		{
			var response = instance.GetCaptchaInfoWithHttpInfo();
			Assert.Null(response.ErrorText);
			Assert.IsType<GetCaptchaInfoResponse>(response.Data);
			Assert.NotEmpty(response.Data?.V2.Variants.Android.SiteKey);
			Assert.NotEmpty(response.Data?.V3.Variants.Invisible.SiteKey);
		}
	}
}
