/*
 * Floatplane REST API
 *
 * The version of the OpenAPI document: 3.9.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FloatplaneAPIClientCSharp.Client;
using FloatplaneAPIClientCSharp.Api;
using FloatplaneAPIClientCSharp.Model;

namespace FloatplaneAPIClientCSharp.Test.Api
{
	/// <summary>
	///  Class for testing CDNV3Api
	/// </summary>
	/// <remarks>
	/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
	/// Please update the test case below to test the API endpoint.
	/// </remarks>
	public class CDNV3ApiTests : IDisposable
	{
		private CDNV3Api instance;

		public CDNV3ApiTests()
		{
			instance = new CDNV3Api();
			ApiTestHelper.SetStrictSerializerSettings(instance, instance.Client);
		}

		public void Dispose()
		{
			// Cleanup when everything is done.
		}

		/// <summary>
		/// Test GetDeliveryInfo - Vod
		/// </summary>
		[Fact]
		public void GetDeliveryInfoOnDemandTest()
		{
			string scenario = "onDemand";
			string? entityId = ApiTestSampleData.Video_New;
			string? outputKind = null;
			var response = instance.GetDeliveryInfoV3WithHttpInfo(scenario, entityId, outputKind);
			Assert.Null(response.ErrorText);
			Assert.IsType<CdnDeliveryV3Response>(response.Data);
			Assert.NotEmpty(response.Data.Groups);
		}

		/// <summary>
		/// Test GetDeliveryInfo - Download
		/// </summary>
		[Fact]
		public void GetDeliveryInfoDownloadTest()
		{
			string scenario = "download";
			string? entityId = ApiTestSampleData.Video_New;
			string? outputKind = null;
			var response = instance.GetDeliveryInfoV3WithHttpInfo(scenario, entityId, outputKind);
			Assert.Null(response.ErrorText);
			Assert.IsType<CdnDeliveryV3Response>(response.Data);
			Assert.NotEmpty(response.Data.Groups);
		}

		/// <summary>
		/// Test GetDeliveryInfo - Livestream
		/// </summary>
		[Fact]
		public void GetDeliveryInfoLivestreamTest()
		{
			string scenario = "live";
			string? entityId = ApiTestSampleData.LttLivesreamId;
			string? outputKind = null;
			var response = instance.GetDeliveryInfoV3WithHttpInfo(scenario, entityId, outputKind);
			Assert.Null(response.ErrorText);
			Assert.IsType<CdnDeliveryV3Response>(response.Data);
			Assert.NotEmpty(response.Data.Groups);
		}
	}
}
