/*
 * Floatplane REST API
 *
 * The version of the OpenAPI document: 3.9.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FloatplaneAPIClientCSharp.Client;
using FloatplaneAPIClientCSharp.Api;
using FloatplaneAPIClientCSharp.Model;

namespace FloatplaneAPIClientCSharp.Test.Api
{
	/// <summary>
	///  Class for testing CDNV2Api
	/// </summary>
	/// <remarks>
	/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
	/// Please update the test case below to test the API endpoint.
	/// </remarks>
	public class CDNV2ApiTests : IDisposable
	{
		private CDNV2Api instance;

		public CDNV2ApiTests()
		{
			instance = new CDNV2Api();
			ApiTestHelper.SetStrictSerializerSettings(instance, instance.Client);
		}

		public void Dispose()
		{
			// Cleanup when everything is done.
		}

		/// <summary>
		/// Test an instance of CDNV2Api
		/// </summary>
		[Fact]
		public void InstanceTest()
		{
			// TODO uncomment below to test 'IsType' CDNV2Api
			//Assert.IsType<CDNV2Api>(instance);
		}

		/// <summary>
		/// Test GetDeliveryInfo - Vod
		/// </summary>
		[Fact]
		public void GetDeliveryInfoVodTest()
		{
			string type = "vod";
			string? guid = ApiTestSampleData.Video_New;
			string? creator = ApiTestSampleData.LttCreatorId;
			var response = instance.GetDeliveryInfoWithHttpInfo(type, guid, creator);
			Assert.Null(response.ErrorText);
			Assert.IsType<CdnDeliveryV2Response>(response.Data);
			Assert.IsType<CdnDeliveryV2VodResponse>(response.Data?.ActualInstance);
			Assert.NotEmpty(response.Data.GetCdnDeliveryV2VodResponse().Cdn);
		}

		/// <summary>
		/// Test GetDeliveryInfo - Download
		/// </summary>
		[Fact]
		public void GetDeliveryInfoDownloadTest()
		{
			string type = "download";
			string? guid = ApiTestSampleData.Video_New;
			string? creator = ApiTestSampleData.LttCreatorId;
			var response = instance.GetDeliveryInfoWithHttpInfo(type, guid, creator);
			Assert.Null(response.ErrorText);
			Assert.IsType<CdnDeliveryV2Response>(response.Data);
			Assert.IsType<CdnDeliveryV2DownloadResponse>(response.Data?.ActualInstance);
			Assert.NotEmpty(response.Data.GetCdnDeliveryV2DownloadResponse().Edges);
		}

		/// <summary>
		/// Test GetDeliveryInfo - Livestream
		/// </summary>
		[Fact]
		public void GetDeliveryInfoLivestreamTest()
		{
			string type = "live";
			string? guid = ApiTestSampleData.Video_New;
			string? creator = ApiTestSampleData.LttCreatorId;
			var response = instance.GetDeliveryInfoWithHttpInfo(type, guid, creator);
			Assert.Null(response.ErrorText);
			Assert.IsType<CdnDeliveryV2Response>(response.Data);
			Assert.IsType<CdnDeliveryV2LivestreamResponse>(response.Data?.ActualInstance);
			Assert.NotEmpty(response.Data.GetCdnDeliveryV2LivestreamResponse().Cdn);
		}
	}
}
