/*
 * Floatplane REST API
 *
 * The version of the OpenAPI document: 3.9.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FloatplaneAPIClientCSharp.Client;
using FloatplaneAPIClientCSharp.Api;
using FloatplaneAPIClientCSharp.Model;

namespace FloatplaneAPIClientCSharp.Test.Api
{
	/// <summary>
	///  Class for testing EdgesV2Api
	/// </summary>
	/// <remarks>
	/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
	/// Please update the test case below to test the API endpoint.
	/// </remarks>
	public class EdgesV2ApiTests : IDisposable
	{
		private EdgesV2Api instance;

		public EdgesV2ApiTests()
		{
			instance = new EdgesV2Api();
			ApiTestHelper.SetStrictSerializerSettings(instance, instance.Client);
		}

		public void Dispose()
		{
			// Cleanup when everything is done.
		}

		/// <summary>
		/// Test an instance of EdgesV2Api
		/// </summary>
		[Fact]
		public void InstanceTest()
		{
			// TODO uncomment below to test 'IsType' EdgesV2Api
			//Assert.IsType<EdgesV2Api>(instance);
		}

		/// <summary>
		/// Test GetEdges
		/// </summary>
		[Fact]
		public void GetEdgesTest()
		{
			#pragma warning disable CS0612
			var response = instance.GetEdgesWithHttpInfo();
			#pragma warning restore CS0612

			Assert.Null(response.ErrorText);
			Assert.IsType<EdgesModel>(response.Data);
		}
	}
}
