/*
 * Floatplane REST API
 *
 * The version of the OpenAPI document: 3.9.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FloatplaneAPIClientCSharp.Client;
using FloatplaneAPIClientCSharp.Api;
using FloatplaneAPIClientCSharp.Model;

namespace FloatplaneAPIClientCSharp.Test.Api
{
	/// <summary>
	///  Class for testing FAQV2Api
	/// </summary>
	/// <remarks>
	/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
	/// Please update the test case below to test the API endpoint.
	/// </remarks>
	public class FAQV2ApiTests : IDisposable
	{
		private FAQV2Api instance;

		public FAQV2ApiTests()
		{
			instance = new FAQV2Api();
			ApiTestHelper.SetStrictSerializerSettings(instance, instance.Client);
		}

		public void Dispose()
		{
			// Cleanup when everything is done.
		}

		/// <summary>
		/// Test an instance of FAQV2Api
		/// </summary>
		[Fact]
		public void InstanceTest()
		{
			// TODO uncomment below to test 'IsType' FAQV2Api
			//Assert.IsType<FAQV2Api>(instance);
		}

		/// <summary>
		/// Test GetFaqSections
		/// </summary>
		[Fact]
		public void GetFaqSectionsTest()
		{
			var response = instance.GetFaqSectionsWithHttpInfo();
			Assert.Null(response.ErrorText);
			Assert.IsType<List<FaqSectionModel>>(response.Data);
			Assert.True(response.Data?.Any());
		}
	}
}
