/*
 * Floatplane REST API
 *
 * The version of the OpenAPI document: 3.9.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FloatplaneAPIClientCSharp.Client;
using FloatplaneAPIClientCSharp.Api;
using FloatplaneAPIClientCSharp.Model;

namespace FloatplaneAPIClientCSharp.Test.Api
{
	/// <summary>
	///  Class for testing LoyaltyRewardsV3Api
	/// </summary>
	/// <remarks>
	/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
	/// Please update the test case below to test the API endpoint.
	/// </remarks>
	public class LoyaltyRewardsV3ApiTests : IDisposable
	{
		private LoyaltyRewardsV3Api instance;

		public LoyaltyRewardsV3ApiTests()
		{
			instance = new LoyaltyRewardsV3Api();
			ApiTestHelper.SetStrictSerializerSettings(instance, instance.Client);
		}

		public void Dispose()
		{
			// Cleanup when everything is done.
		}

		/// <summary>
		/// Test ListCreatorLoyaltyReward
		/// </summary>
		[Fact]
		public void ListCreatorLoyaltyRewardTest()
		{
			var response = instance.ListCreatorLoyaltyRewardWithHttpInfo();
			Assert.Null(response.ErrorText);
			Assert.IsType<List<Object>>(response.Data);
			// Assert.True(response.Data?.Any()); // Currently can't test this is returning anything back with user accounts.
		}
	}
}
