/*
 * Floatplane REST API
 *
 * The version of the OpenAPI document: 3.9.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FloatplaneAPIClientCSharp.Client;
using FloatplaneAPIClientCSharp.Api;
using FloatplaneAPIClientCSharp.Model;

namespace FloatplaneAPIClientCSharp.Test.Api
{
	/// <summary>
	///  Class for testing PaymentsV2Api
	/// </summary>
	/// <remarks>
	/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
	/// Please update the test case below to test the API endpoint.
	/// </remarks>
	public class PaymentsV2ApiTests : IDisposable
	{
		private PaymentsV2Api instance;

		public PaymentsV2ApiTests()
		{
			instance = new PaymentsV2Api();
			ApiTestHelper.SetStrictSerializerSettings(instance, instance.Client);
		}

		public void Dispose()
		{
			// Cleanup when everything is done.
		}

		/// <summary>
		/// Test an instance of PaymentsV2Api
		/// </summary>
		[Fact]
		public void InstanceTest()
		{
			// TODO uncomment below to test 'IsType' PaymentsV2Api
			//Assert.IsType<PaymentsV2Api>(instance);
		}

		/// <summary>
		/// Test ListAddresses
		/// </summary>
		[Fact]
		public void ListAddressesTest()
		{
			var response = instance.ListAddressesWithHttpInfo();
			Assert.Null(response.ErrorText);
			Assert.IsType<List<PaymentAddressModel>>(response.Data);
			Assert.True(response.Data?.Any());
		}

		/// <summary>
		/// Test ListInvoices
		/// </summary>
		[Fact]
		public void ListInvoicesTest()
		{
			var response = instance.ListInvoicesWithHttpInfo();
			Assert.Null(response.ErrorText);
			Assert.IsType<PaymentInvoiceListV2Response>(response.Data);
			Assert.True(response.Data?.Invoices.Any());
		}

		/// <summary>
		/// Test ListPaymentMethods
		/// </summary>
		[Fact]
		public void ListPaymentMethodsTest()
		{
			var response = instance.ListPaymentMethodsWithHttpInfo();
			Assert.Null(response.ErrorText);
			Assert.IsType<List<PaymentMethodModel>>(response.Data);
			Assert.True(response.Data?.Any());
		}
	}
}
