/*
 * Floatplane REST API
 *
 * The version of the OpenAPI document: 3.9.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FloatplaneAPIClientCSharp.Client;
using FloatplaneAPIClientCSharp.Api;
// uncomment below to import models
//using FloatplaneAPIClientCSharp.Model;

namespace FloatplaneAPIClientCSharp.Test.Api
{
	/// <summary>
	///  Class for testing PollV3Api
	/// </summary>
	/// <remarks>
	/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
	/// Please update the test case below to test the API endpoint.
	/// </remarks>
	public class PollV3ApiTests : IDisposable
	{
		private PollV3Api instance;

		public PollV3ApiTests()
		{
			instance = new PollV3Api();
			ApiTestHelper.SetStrictSerializerSettings(instance, instance.Client);
		}

		public void Dispose()
		{
			// Cleanup when everything is done.
		}

		/// <summary>
		/// Test JoinLiveRoom
		/// </summary>
		[Fact]
		public void JoinLiveRoomTest()
		{
			// TODO uncomment below to test the method and replace null with proper value
			//var response = instance.JoinLiveRoom();
			//Assert.IsType<Object>(response);
		}

		/// <summary>
		/// Test LeaveLiveRoom
		/// </summary>
		[Fact]
		public void LeaveLiveRoomTest()
		{
			// TODO uncomment below to test the method and replace null with proper value
			//var response = instance.LeaveLiveRoom();
			//Assert.IsType<Object>(response);
		}

		/// <summary>
		/// Test VotePoll
		/// </summary>
		[Fact]
		public void VotePollTest()
		{
			// TODO uncomment below to test the method and replace null with proper value
			//VotePollRequest votePollRequest = null;
			//var response = instance.VotePoll(votePollRequest);
			//Assert.IsType<Object>(response);
		}
	}
}
