/*
 * Floatplane REST API
 *
 * The version of the OpenAPI document: 3.9.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FloatplaneAPIClientCSharp.Client;
using FloatplaneAPIClientCSharp.Api;
//using FloatplaneAPIClientCSharp.Model;

namespace FloatplaneAPIClientCSharp.Test.Api
{
	/// <summary>
	///  Class for testing SocketV3Api
	/// </summary>
	/// <remarks>
	/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
	/// Please update the test case below to test the API endpoint.
	/// </remarks>
	public class SocketV3ApiTests : IDisposable
	{
		private SocketV3Api instance;

		public SocketV3ApiTests()
		{
			instance = new SocketV3Api();
			ApiTestHelper.SetStrictSerializerSettings(instance, instance.Client);
		}

		public void Dispose()
		{
			// Cleanup when everything is done.
		}

		/// <summary>
		/// Test DisconnectSocket
		/// </summary>
		[Fact]
		public void DisconnectSocketTest()
		{
			// TODO uncomment below to test the method and replace null with proper value
			//var response = instance.DisconnectSocket();
			//Assert.IsType<Object>(response);
		}

		/// <summary>
		/// Test SocketConnect
		/// </summary>
		[Fact]
		public void SocketConnectTest()
		{
			// TODO uncomment below to test the method and replace null with proper value
			//var response = instance.SocketConnect();
			//Assert.IsType<Object>(response);
		}
	}
}
