/*
 * Floatplane REST API
 *
 * The version of the OpenAPI document: 3.9.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FloatplaneAPIClientCSharp.Client;
using FloatplaneAPIClientCSharp.Api;
using FloatplaneAPIClientCSharp.Model;

namespace FloatplaneAPIClientCSharp.Test.Api
{
	/// <summary>
	///  Class for testing SubscriptionsV3Api
	/// </summary>
	/// <remarks>
	/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
	/// Please update the test case below to test the API endpoint.
	/// </remarks>
	public class SubscriptionsV3ApiTests : IDisposable
	{
		private SubscriptionsV3Api instance;

		public SubscriptionsV3ApiTests()
		{
			instance = new SubscriptionsV3Api();
			ApiTestHelper.SetStrictSerializerSettings(instance, instance.Client);
		}

		public void Dispose()
		{
			// Cleanup when everything is done.
		}

		/// <summary>
		/// Test an instance of SubscriptionsV3Api
		/// </summary>
		[Fact]
		public void InstanceTest()
		{
			// TODO uncomment below to test 'IsType' SubscriptionsV3Api
			//Assert.IsType<SubscriptionsV3Api>(instance);
		}

		/// <summary>
		/// Test ListUserSubscriptionsV3
		/// </summary>
		[Fact]
		public void ListUserSubscriptionsV3Test()
		{
			var response = instance.ListUserSubscriptionsV3WithHttpInfo();
			Assert.Null(response.ErrorText);
			Assert.IsType<List<UserSubscriptionModel>>(response.Data);
			Assert.True(response.Data?.Any());
		}
	}
}
