# Not all of these work for the Community Edition of Redoc
referenceDocs:
  expandDefaultServerVariables: true
  pagination: section
  showConsole: true
  showNextbutton: true
  theme:
    menu:
      backgroundColor: '#ffffff'
    colors:
      primary:
        main: blue